version: "3"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - registry-data:/app/registry_files
    depends_on:
      - mssql
    environment:
      ASPNETCORE_ENVIRONMENT: Production
  
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-CU14-ubuntu"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: "Test@123"
      ACCEPT_EULA: "Y"
      
volumes:
  registry-data:
  mssql-data:
