version: "3"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - "${REGISTRY_FILES_LOCATION}:/app/registry_files"
      - "${AWS_CREDENTIAL_FILE_LOCATION}:/home/.aws/credentials"
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS_PROFILE=sns-admin
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  proxy:
    image: nginx:latest
    depends_on:
      - web
    volumes:
      - /Users/ioneuk/Documents/diplom/RegistryManagementV3/RegistryManagementV3/nginx.info:/etc/nginx/nginx.conf
    ports:
      - "81:81"
  
  mssql:
    image: "mcr.microsoft.com/mssql/server:2017-CU14-ubuntu"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql
    environment:
      SA_PASSWORD: "Test@123"
      ACCEPT_EULA: "Y"
      
volumes:
  registry-data:
  mssql-data:
